# Dockerfile for vsftpd on CentOS
FROM centos:7
RUN yum -y update; yum -y install which vsftpd net-tools vsftpd-sysvinit; yum clean all

COPY vusers.txt /etc/vsftpd/
RUN db_load -T -t hash -f /etc/vsftpd/vusers.txt /etc/vsftpd/vsftpd-virtual-user.db; rm -v /etc/vsftpd/vusers.txt; \ 
	chmod 600 /etc/vsftpd/vsftpd-virtual-user.db
COPY vsftpd.conf /etc/vsftpd/
COPY vsftpd.virtual /etc/iam.d/

RUN mkdir -p /home/vsftpd/anonymous;chmod -R 777 /home/vsftpd/anonymous; chown -R ftp:ftp /home/vsftpd

EXPOSE 20 21 30000 31000

